/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
/* Header for class ai_implementation_a_AIImplementationA */

#ifndef _Included_AIImplementationA
#define _Included_AIImplementationA
#ifdef __c
extern "C" {
#endif
/*
 * Class:     ai_implementation_a_AIImplementationA
 * Method:    callCImplementation
 * Signature: (Lrobot/RobotControl;Lmain_application/GUIManage;)V
 */
JNIEXPORT void JNICALL Java_AIImplementationA_callCImplementation
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __c
}
#endif
#endif
